// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu2HCiVeaAW8V95OcPQtfjTa2SsiZKFMY',
    appId: '1:722410554111:web:50de288d8ccddcb3a4c2ca',
    messagingSenderId: '722410554111',
    projectId: 'flutter-chat-app-7ba40',
    authDomain: 'flutter-chat-app-7ba40.firebaseapp.com',
    storageBucket: 'flutter-chat-app-7ba40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7wnTWe6numrgsyVpxXQ7BGCZRlagtMKw',
    appId: '1:722410554111:ios:38249ccf4159885ca4c2ca',
    messagingSenderId: '722410554111',
    projectId: 'flutter-chat-app-7ba40',
    storageBucket: 'flutter-chat-app-7ba40.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7wnTWe6numrgsyVpxXQ7BGCZRlagtMKw',
    appId: '1:722410554111:ios:38249ccf4159885ca4c2ca',
    messagingSenderId: '722410554111',
    projectId: 'flutter-chat-app-7ba40',
    storageBucket: 'flutter-chat-app-7ba40.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu2HCiVeaAW8V95OcPQtfjTa2SsiZKFMY',
    appId: '1:722410554111:web:2bf97362b3325506a4c2ca',
    messagingSenderId: '722410554111',
    projectId: 'flutter-chat-app-7ba40',
    authDomain: 'flutter-chat-app-7ba40.firebaseapp.com',
    storageBucket: 'flutter-chat-app-7ba40.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg58-umtmPP5uiv6mRSaPrrr2gvaPVYiM',
    appId: '1:722410554111:android:1f4f56167ae81e9da4c2ca',
    messagingSenderId: '722410554111',
    projectId: 'flutter-chat-app-7ba40',
    storageBucket: 'flutter-chat-app-7ba40.firebasestorage.app',
  );

}